#!/bin/bash
echo "🔌 TP-Link Connected Pironman Guide"
echo "===================================="
echo ""

echo "📋 What we know:"
echo "  • You have 2 Pironman Pi 5s connected via TP-Link ethernet"
echo "  • octavia: Has Hailo + NVMe, last seen at .81 (disk full)"
echo "  • anastasia: Basic setup, location unknown"
echo "  • Main network: 192.168.4.0/24 (eero at .1)"
echo ""

echo "🔍 Likely scenarios:"
echo ""
echo "1. TP-Link is a SWITCH (most likely):"
echo "   → Pironmans get IPs from main eero: 192.168.4.x"
echo "   → Should be visible in current scans"
echo "   → Check router DHCP leases"
echo ""
echo "2. TP-Link is a ROUTER with NAT:"
echo "   → Pironmans on different subnet (192.168.0.x or 192.168.1.x)"
echo "   → Need to connect to TP-Link first"
echo "   → Then access Pironmans through it"
echo ""

echo "🎯 Quick Actions:"
echo ""
echo "Option A - Check eero app/web for ALL connected devices"
echo "  1. Open eero app on phone"
echo "  2. Look for devices named 'octavia' or 'anastasia'"
echo "  3. Check for any 'Raspberry Pi' devices"
echo "  4. Note their IP addresses"
echo ""
echo "Option B - If TP-Link has management interface:"
echo "  1. Find TP-Link IP (check device label, often 192.168.0.1)"
echo "  2. Access web interface"
echo "  3. Check connected devices"
echo "  4. Look for MAC addresses starting with: dc:a6:32 (Pi 5)"
echo ""
echo "Option C - Physical check:"
echo "  1. Look at TP-Link switch"
echo "  2. Note which ethernet ports have link LEDs lit"
echo "  3. Trace cables to Pironman cases"
echo "  4. Connect monitor to each Pironman"
echo "  5. Check IP with: hostname -I"
echo ""

echo "🔑 SSH Commands to try once you have IPs:"
echo "  ssh -i ~/.ssh/id_octavia pi@<IP>"
echo "  ssh -i ~/.ssh/id_ed25519 pi@<IP>"
echo "  ssh octavia@<IP>"
echo "  ssh anastasia@<IP>"
echo ""

echo "💡 Raspberry Pi 5 MAC prefix: dc:a6:32"
echo "   Look for MACs starting with this in router"
