#!/bin/bash

echo "🚀 BlackRoad AI Dashboard Deployment Guide"
echo "============================================"
echo ""
echo "✅ Build Complete: Static files ready in out/"
echo "✅ GitHub Repo: https://github.com/blackboxprogramming/blackroad-ai-dashboard"
echo ""
echo "📋 DEPLOY TO CLOUDFLARE PAGES:"
echo ""
echo "1. Open: https://dash.cloudflare.com"
echo "2. Go to: Pages > Create a project"
echo "3. Click: Connect to Git"
echo "4. Select: blackboxprogramming/blackroad-ai-dashboard"
echo "5. Configure build:"
echo "   - Framework preset: Next.js"
echo "   - Build command: npm run build"
echo "   - Build output directory: out"
echo "   - Node version: 20"
echo "6. Click: Save and Deploy"
echo "7. After deployment, add custom domain:"
echo "   - Go to project > Custom domains"
echo "   - Add: ai.blackroad.io"
echo ""
echo "🎯 Once deployed, your AI agent dashboard will be live at:"
echo "   https://ai.blackroad.io"
echo ""
echo "✨ Dashboard Features:"
echo "   - 9 AI agents displayed"
echo "   - 3 teams organized"
echo "   - Chat interface for each agent"
echo "   - Real-time status indicators"
echo "   - Responsive design"
echo ""
echo "🤖 Agents Ready:"
echo "   Infrastructure: Lucidia, Marcus, Viktor, Sophia"
echo "   Creative: CECE, Luna, Dante"  
echo "   Coding: Aria-Prime, Aria-Tiny"
echo ""
