#!/bin/bash
echo "🏥 Pironman Diagnostic - Powered On But Not Responding"
echo "======================================================"
echo ""

echo "📋 Symptoms:"
echo "  • Pironmans are powered on (confirmed by user)"
echo "  • Not responding to ping"
echo "  • No MAC addresses visible in ARP"
echo "  • No SSH connections successful"
echo ""

echo "🤔 Possible Causes:"
echo ""
echo "1. Boot Failure (most likely for octavia):"
echo "   → Disk full prevents complete boot"
echo "   → Network stack doesn't start"
echo "   → Need monitor/keyboard to see errors"
echo ""
echo "2. Different Subnet:"
echo "   → TP-Link configured as router with NAT"
echo "   → Pironmans on 192.168.0.x or 192.168.1.x"
echo "   → Need to access TP-Link management first"
echo ""
echo "3. SSH Not Enabled:"
echo "   → Fresh install without SSH configured"
echo "   → Need to enable via raspi-config"
echo "   → Requires monitor/keyboard access"
echo ""
echo "4. Firewall/Network Config:"
echo "   → Pi firewall blocking connections"
echo "   → Static IP misconfigured"
echo "   → Wrong gateway/subnet mask"
echo ""

echo "🎯 SOLUTIONS:"
echo ""
echo "═══ IMMEDIATE ACTION (Physical Access) ═══"
echo ""
echo "Connect HDMI + Keyboard to each Pironman:"
echo "  1. Watch what's on screen - is it booted?"
echo "  2. Check if login prompt appears"
echo "  3. Login and check network:"
echo "     → hostname -I          # What's my IP?"
echo "     → ip addr show         # Network config"
echo "     → sudo systemctl status ssh   # Is SSH running?"
echo "     → df -h                # Disk space"
echo ""
echo "If octavia is stuck at boot:"
echo "  1. Power off"
echo "  2. Hold SHIFT while powering on (recovery menu)"
echo "  3. Or edit /boot/cmdline.txt: add 'init=/bin/bash'"
echo "  4. Clean disk space"
echo "  5. Reboot"
echo ""

echo "═══ CHECK TP-LINK DEVICE ═══"
echo ""
echo "1. Find TP-Link physical device"
echo "2. Check for management IP on label"
echo "3. Access web interface from browser"
echo "4. Look at DHCP client list"
echo "5. Check if Pironmans got IPs there"
echo ""

echo "═══ ENABLE SSH (if needed) ═══"
echo ""
echo "If you can login via keyboard but SSH isn't working:"
echo "  sudo systemctl enable ssh"
echo "  sudo systemctl start ssh"
echo "  sudo ufw allow 22   # if firewall enabled"
echo ""

echo "═══ CHECK FROM PIRONMAN CONSOLE ═══"
echo ""
echo "Once logged in via keyboard:"
echo "  # What's my IP?"
echo "  hostname -I"
echo "  "
echo "  # Can I reach the Mac?"
echo "  ping 192.168.4.28"
echo "  "
echo "  # Is SSH running?"
echo "  sudo systemctl status ssh"
echo "  "
echo "  # Network config"
echo "  ip addr show eth0"
echo "  "
echo "  # Check routes"
echo "  ip route"
echo ""

echo "💡 MOST LIKELY: octavia has disk full and can't complete boot"
echo "   → Connect monitor to see boot errors"
echo "   → Boot to recovery"
echo "   → Clear disk space"
echo "   → Normal boot should work then"
echo ""

echo "📞 Report back what you see on the monitors!"
