#!/bin/bash
echo "🔧 Headless Pironman Recovery Options"
echo "======================================"
echo ""

echo "Since Pironmans are headless and not on network, you have these options:"
echo ""

echo "═══ OPTION 1: Remove Storage & Mount on Mac ═══"
echo ""
echo "For octavia (NVMe + disk full issue):"
echo "  1. Power off octavia"
echo "  2. Remove NVMe drive from Pironman case"
echo "  3. Connect NVMe to Mac via USB-C adapter"
echo "  4. Mount the root partition"
echo "  5. Delete large files to free space:"
echo "     - /var/log/*.log"
echo "     - /var/lib/docker (if huge)"
echo "     - journalctl logs"
echo "  6. Reinstall NVMe in octavia"
echo "  7. Power on - should boot now"
echo ""

echo "═══ OPTION 2: Access via TP-Link Management ═══"
echo ""
echo "If TP-Link is a managed switch/router:"
echo "  1. Find TP-Link physical device"
echo "  2. Note model number"
echo "  3. Look up default management IP (label or manual)"
echo "  4. Access web interface in browser"
echo "  5. Check connected devices / DHCP clients"
echo "  6. Find Pironman IPs there"
echo ""

echo "═══ OPTION 3: Scan from Working Pi ═══"
echo ""
echo "Use alice or lucidia to scan for them:"
echo "  ssh alice"
echo "  sudo nmap -sn 192.168.4.0/24"
echo "  arp -a"
echo "  # Look for unknown devices"
echo ""

echo "═══ OPTION 4: Check if Different Subnet ═══"
echo ""
echo "TP-Link might have created 192.168.0.x or 192.168.1.x:"
echo "  1. Find TP-Link gateway IP (on device label)"
echo "  2. Try accessing: http://192.168.0.1 or http://192.168.1.1"
echo "  3. Login (usually admin/admin or printed on device)"
echo "  4. Check connected devices list"
echo ""

echo "═══ OPTION 5: Serial Console (Advanced) ═══"
echo ""
echo "If Pironman has GPIO pins exposed:"
echo "  1. Use USB-to-serial adapter"
echo "  2. Connect to UART pins on Pi 5"
echo "  3. Use screen or minicom to access console"
echo "  4. Baud rate: 115200"
echo ""

echo "═══ MOST PRACTICAL: Option 1 (Remove NVMe) ═══"
echo ""
echo "For octavia specifically:"
echo "  • Known issue: disk full"
echo "  • Has NVMe drive (easy to remove)"
echo "  • Can mount on Mac and clean up"
echo "  • Should boot fine after cleanup"
echo ""

echo "Would you like to:"
echo "  A) Try removing octavia's NVMe to clean it?"
echo "  B) Find TP-Link management interface?"
echo "  C) Scan more aggressively from working Pis?"
