#!/bin/bash

# Automated Cloudflare DNS Setup for blackroad.io → Railway
# This script creates/updates DNS records for br-apps services

set -e

CF_TOKEN='yP5h0HvsXX0BpHLs01tLmgtTbQurIKPL4YnQfIwy'
CF_ZONE='848cf0b18d51e0170e0d1537aec3505a'

echo "☁️  Cloudflare DNS Automation for blackroad.io"
echo "================================================"
echo ""

# Function to create or update DNS record
upsert_dns_record() {
  local name="$1"
  local target="$2"
  local proxy="${3:-true}"
  local record_type="CNAME"

  echo "📝 Processing: ${name}.blackroad.io → $target"

  # Handle root domain (@)
  local lookup_name="${name}.blackroad.io"
  if [ "$name" = "@" ]; then
    lookup_name="blackroad.io"
  fi

  # Check if record exists
  EXISTING=$(curl -s -X GET \
    "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/dns_records?name=${lookup_name}&type=${record_type}" \
    -H "Authorization: Bearer ${CF_TOKEN}" \
    -H "Content-Type: application/json")

  RECORD_ID=$(echo "$EXISTING" | jq -r '.result[0].id // empty')
  SUCCESS=$(echo "$EXISTING" | jq -r '.success')

  if [ "$SUCCESS" != "true" ]; then
    echo "   ❌ Error fetching existing record"
    echo "$EXISTING" | jq '.errors'
    return 1
  fi

  if [ -n "$RECORD_ID" ] && [ "$RECORD_ID" != "null" ]; then
    # Update existing record
    echo "   🔄 Updating existing record (ID: ${RECORD_ID})"
    RESPONSE=$(curl -s -X PATCH \
      "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/dns_records/${RECORD_ID}" \
      -H "Authorization: Bearer ${CF_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "{
        \"type\": \"${record_type}\",
        \"name\": \"${name}\",
        \"content\": \"${target}\",
        \"proxied\": ${proxy},
        \"ttl\": 1
      }")
  else
    # Create new record
    echo "   ➕ Creating new record"
    RESPONSE=$(curl -s -X POST \
      "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/dns_records" \
      -H "Authorization: Bearer ${CF_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "{
        \"type\": \"${record_type}\",
        \"name\": \"${name}\",
        \"content\": \"${target}\",
        \"proxied\": ${proxy},
        \"ttl\": 1
      }")
  fi

  RESPONSE_SUCCESS=$(echo "$RESPONSE" | jq -r '.success')
  if [ "$RESPONSE_SUCCESS" = "true" ]; then
    echo "   ✅ Success!"
  else
    echo "   ❌ Failed!"
    echo "$RESPONSE" | jq '.errors'
  fi
  echo ""
}

# Get Railway domains from user
echo "⚠️  You need the Railway domains from your deployed services"
echo ""
echo "To find them:"
echo "  1. Go to https://railway.app/dashboard"
echo "  2. Open the br-apps project"
echo "  3. Click each service → Settings → Networking"
echo "  4. Copy the 'Public Domain' (e.g., web-production.up.railway.app)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -p "Enter Railway domain for WEB service (e.g., web-production.up.railway.app): " WEB_DOMAIN
read -p "Enter Railway domain for API service (e.g., api-production.up.railway.app): " API_DOMAIN

# Validate inputs
if [ -z "$WEB_DOMAIN" ] || [ -z "$API_DOMAIN" ]; then
  echo ""
  echo "❌ Error: Both domains are required!"
  exit 1
fi

# Confirm before proceeding
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ready to create these DNS records:"
echo ""
echo "  www.blackroad.io  → $WEB_DOMAIN"
echo "  blackroad.io (@)  → $WEB_DOMAIN"
echo "  api.blackroad.io  → $API_DOMAIN"
echo ""
read -p "Continue? (y/n): " CONFIRM

if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
  echo "Aborted."
  exit 0
fi

echo ""
echo "🚀 Creating/updating DNS records..."
echo ""

# Create records
upsert_dns_record "www" "$WEB_DOMAIN" "true"
upsert_dns_record "@" "$WEB_DOMAIN" "true"
upsert_dns_record "api" "$API_DOMAIN" "true"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ DNS setup complete!"
echo ""
echo "🔗 Your domains:"
echo "   https://www.blackroad.io"
echo "   https://blackroad.io"
echo "   https://api.blackroad.io"
echo ""
echo "⏱  DNS propagation: ~5-10 minutes"
echo "🔒 SSL certificates: Auto-generated by Railway"
echo ""
echo "🧪 Test with:"
echo "   curl -I https://www.blackroad.io"
echo "   curl -I https://api.blackroad.io"
echo ""
echo "📊 View records: https://dash.cloudflare.com/${CF_ZONE}/dns"
echo ""
