name: "Security Audit"

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  npm-audit:
    name: NPM Security Audit
    runs-on: ubuntu-latest
    if: hashFiles('package.json') != ''
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

  pip-audit:
    name: Python Security Audit
    runs-on: ubuntu-latest
    if: hashFiles('requirements.txt', 'setup.py', 'pyproject.toml') != ''
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install pip-audit
        run: pip install pip-audit
      
      - name: Run pip-audit
        run: pip-audit
        continue-on-error: true
