#!/usr/bin/env bash
# Automatic README generator for projects
set -euo pipefail

PROJECT_DIR="${1:-.}"
cd "$PROJECT_DIR"
PROJECT_NAME=$(basename "$PROJECT_DIR")

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}[AUTO-README]${NC} Generating README for $PROJECT_NAME..."

# Detect project type
PACKAGE_JSON=$(test -f package.json && echo "yes" || echo "no")
PYTHON=$(test -f requirements.txt && echo "yes" || echo "no")
GO=$(test -f go.mod && echo "yes" || echo "no")

# Get git info
REPO_URL=$(git remote get-url origin 2>/dev/null || echo "")
BRANCH=$(git branch --show-current 2>/dev/null || echo "main")
LAST_COMMIT=$(git log -1 --format="%h - %s" 2>/dev/null || echo "No commits yet")

# Generate README
cat > README.md <<README
# 🚀 ${PROJECT_NAME}

**Auto-generated README** - Last updated: $(date '+%Y-%m-%d %H:%M:%S')

## 📦 Project Info

- **Repository**: ${REPO_URL}
- **Branch**: ${BRANCH}
- **Last Commit**: ${LAST_COMMIT}

## 🔥 Features

✅ Auto-deploy enabled (commits push automatically)
✅ Watch mode compatible (continuous auto-save)
✅ Webhook notifications (deployment tracking)
✅ CI/CD ready (GitHub Actions support)

## 🚀 Quick Start

\`\`\`bash
# Clone the repository
git clone ${REPO_URL}
cd ${PROJECT_NAME}
README

# Add language-specific instructions
if [[ "$PACKAGE_JSON" == "yes" ]]; then
  cat >> README.md <<NODEJS

# Install dependencies
npm install

# Run development server
npm run dev

# Build for production
npm run build

# Run tests
npm test
NODEJS
fi

if [[ "$PYTHON" == "yes" ]]; then
  cat >> README.md <<PYTHON

# Install dependencies
pip install -r requirements.txt

# Run the application
python main.py
PYTHON
fi

if [[ "$GO" == "yes" ]]; then
  cat >> README.md <<GOLANG

# Install dependencies
go mod download

# Build
go build

# Run
./${PROJECT_NAME}
GOLANG
fi

cat >> README.md <<'FOOTER'
```

## 🔧 Auto-Deploy Usage

This project uses BlackRoad auto-deploy system:

```bash
# Make changes
echo "console.log('new feature');" >> feature.js

# Auto-commit and push
./.git-auto-commit.sh "Added new feature"

# Or just use git - it auto-pushes!
git add .
git commit -m "changes"
```

## 📊 Project Stats

- **Auto-deploy**: ✅ Enabled
- **Webhooks**: ✅ Active
- **Watch mode**: ✅ Available
- **CI/CD**: ✅ Ready

## 🎯 Powered By

BlackRoad OS Auto-Deploy System 🚀

---

*Auto-generated by BlackRoad README Generator*
FOOTER

echo -e "${GREEN}✓${NC} README.md generated!"
echo ""
echo "Commit it:"
echo "  ./.git-auto-commit.sh 'Generated README'"
