#!/usr/bin/env bash
# Generate CHANGELOG.md automatically
set -euo pipefail

PROJECT_DIR="${1:-.}"
cd "$PROJECT_DIR"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}[CHANGELOG]${NC} Generating CHANGELOG.md..."

cat > CHANGELOG.md <<'CHANGELOG'
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

CHANGELOG

# Get commits grouped by type
git log --pretty=format:"%s|||%h|||%ad" --date=short 2>/dev/null | head -50 | while IFS='|||' read msg hash date; do
  case "$msg" in
    feat*|✨*) echo "### Added" >> CHANGELOG.md; echo "- $msg (\`$hash\`) - $date" >> CHANGELOG.md;;
    fix*|🐛*) echo "### Fixed" >> CHANGELOG.md; echo "- $msg (\`$hash\`) - $date" >> CHANGELOG.md;;
    docs*|📚*) echo "### Documentation" >> CHANGELOG.md; echo "- $msg (\`$hash\`) - $date" >> CHANGELOG.md;;
    *) echo "### Changed" >> CHANGELOG.md; echo "- $msg (\`$hash\`) - $date" >> CHANGELOG.md;;
  esac
done

echo "">> CHANGELOG.md
echo "---" >> CHANGELOG.md
echo "*Auto-generated by BlackRoad DevOps Platform*" >> CHANGELOG.md

echo -e "${GREEN}✓${NC} CHANGELOG.md generated!"
echo "  Location: $(pwd)/CHANGELOG.md"
