export const STRIPE_PRODUCTS = {
  developer: {
    id: 'developer',
    name: 'Developer',
    price: 0,
    period: 'forever',
    features: [
      'Up to 10 concurrent agents',
      'Lucidia agents (rate-limited)',
      'Basic Prism Console',
      'Community support',
      '1 GB RoadChain storage',
      '1,000 API requests/day',
    ],
  },
  professional: {
    id: 'professional',
    name: 'Professional',
    price: 499,
    period: 'month',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PROFESSIONAL || 'price_professional',
    features: [
      'Up to 1,000 concurrent agents',
      'Unlimited Lucidia agents',
      'Advanced Prism Console',
      'Email & chat support (24h)',
      '100 GB RoadChain storage',
      '10,000 API requests/day',
      '99.5% uptime SLA',
      '5 team members included',
    ],
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise',
    price: null,
    period: 'custom',
    contactSales: true,
    features: [
      'Unlimited concurrent agents',
      'Dedicated infrastructure',
      '24/7 phone & Slack support',
      'Unlimited team members',
      'HIPAA/SOC 2/FedRAMP ready',
      'On-premise deployment option',
      'Up to 99.99% SLA',
      'Unlimited storage',
    ],
  },
}
